truncate table stage.stage_ingreso_historia;

insert into stage.stage_ingreso_historia
select
poliza,
cheque,
tran,
fecha_operacion::date,
mes_operacion,
monto,
cuenta,
upper(nombre_cuenta) as nombre_cuenta,
upper(cuenta_consolidadora) as cuenta_consolidadora,
upper(cuenta_resumen) as cuenta_resumen,
upper(estado_financiero) as estado_financiero,
posicion,
clasificacion,
debe,
haber,
serie_factura,
no_factura,
fecha_factura::date,
nit,
upper(nombre_proveedor) as nombre_proveedor,
upper(regimen) as regimen,
upper(libro) as libro,
upper(tipo_doc) as tipo_doc,
factura_compras,
upper(tipo_registro) as tipo_registro,
galones,
tipo_combustible,
servicio,
bien_compras,
servicio_ventas,
bien_ventas,
combustible,
importacion,
exportacion,
excento,
compra_servicio_pc,
idp,
iva_lc_lv,
total,
upper(comentario) as comentario,
upper(nombre_poliza) as nombre_poliza,
debe_2,
haber_2,
saldo_inicial
from stage.stage_ingreso
where poliza is not null;